CREATE DATABASE DBMyFellowGamer
GO
USE DBMyFellowGamer
GO
CREATE TABLE Tb_User (
	ID INT IDENTITY (1, 1),
	Username NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	PIN NVARCHAR(200) NOT NULL,
	TermsOfUse BIT NOT NULL,	
	PrivacyPolicy BIT NOT NULL,
	CreationDate DATETIME NOT NULL,

	CONSTRAINT PK_Tb_User PRIMARY KEY (ID)
)