USE DBMyFellowGamer
GO
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Tb_User') )
BEGIN
	CREATE TABLE Tb_User (
		ID INT IDENTITY (1, 1),
		Username NVARCHAR(50) NOT NULL,
		Email NVARCHAR(100) NOT NULL,
		PIN NVARCHAR(200) NOT NULL,
		TermsOfUse BIT NOT NULL,	
		PrivacyPolicy BIT NOT NULL,
		CreationDate DATETIME NOT NULL,
	
		CONSTRAINT PK_Tb_User PRIMARY KEY (ID)
	)
END
ELSE
BEGIN
	PRINT 'Tabela já existe!';
END